/**
 * The trail's geometry.
 *
 * IT USED TO PARSE SHAPES OUT OF A STYLESHEET, because the path was a tiled SVG frozen into a data
 * URI in `trail.css` and there was nowhere else to look at it. It is now generated by a pure function
 * from the measured waypoint positions, which means these assertions can be made against the real
 * thing instead of against a string. That is most of why the rewrite was worth doing twice.
 *
 * What matters about this curve, and what each of these covers:
 *
 *   IT MUST VISIT EVERY WAYPOINT. The discs are laid out by CSS and the curve is generated in JS; if
 *   they disagree, the page shows discs floating beside a path instead of on it.
 *   IT MUST STAY IN ITS BOX. An SVG clips at its viewBox rather than overflowing, so a curve that
 *   strays gets shaved to a flat edge — which is what happened when the loop radius was capped at the
 *   reach instead of half of it.
 *   IT MUST HAVE NO SHARP POINTS. Guaranteed by centripetal Catmull-Rom, and asserted here, because
 *   the uniform form it replaced produced visible cusps at every loop.
 *   IT MUST ACTUALLY LOOP. Every other assertion would pass on a plain wave.
 *   IT MUST NOT REPEAT, which was the whole complaint about the tiled version.
 *   IT MUST BE STABLE. It is regenerated on every reflow, so a FAQ row opening must not redraw the
 *   whole page's trail.
 */

import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'
import { estimatedStops, knotsToPath, trailKnots, trailPath } from '../src/lib/trailPath.js'
import { arcLength, cubicPoint, parseCubicPath, tangents } from '../scripts/path-math.js'

/** A realistic geometry: eight discs plus the summit mark, in a 320px-wide page's band. */
const WIDTH = 64
const MEAN = 40
const STOPS = [0, 470, 900, 1180, 1610, 2040, 2600, 3150, 3520]

function build(overrides = {}) {
  const options = { stops: STOPS, width: WIDTH, meanX: MEAN, ...overrides }
  return { options, knots: trailKnots(options), segments: parseCubicPath(trailPath(options)) }
}

/** Dense samples along the whole curve. */
function sample(segments, per = 60) {
  return segments.flatMap((segment) =>
    Array.from({ length: per }, (_, i) => cubicPoint(segment, i / per)),
  )
}

describe('visiting the waypoints', () => {
  const { knots, segments } = build()

  it('passes exactly through the mean line at every stop', () => {
    /* Catmull-Rom interpolates its knots, so each knot IS a segment endpoint. Checking the emitted
       path rather than the knot list is what makes this a test of the curve and not of the input. */
    const onCurve = [segments[0][0], ...segments.map((segment) => segment[3])]
    for (const stop of STOPS) {
      const hit = onCurve.find(
        ([x, y]) => Math.abs(x - MEAN) < 0.02 && Math.abs(y - stop) < 0.02,
      )
      expect(hit, `no on-curve point at the disc at y=${stop}`).toBeTruthy()
    }
  })

  it('starts at the first stop and ends at the last', () => {
    expect(knots[0]).toEqual({ x: MEAN, y: STOPS[0] })
    expect(knots[knots.length - 1]).toEqual({ x: MEAN, y: STOPS[STOPS.length - 1] })
  })

  it('returns nothing for a degenerate set of stops rather than throwing', () => {
    expect(trailKnots({ stops: [], width: WIDTH, meanX: MEAN })).toEqual([])
    expect(trailKnots({ stops: [10], width: WIDTH, meanX: MEAN })).toEqual([])
    expect(trailPath({ stops: [0, 0], width: WIDTH, meanX: MEAN })).toBe('')
  })

  it('skips a zero-height span instead of dividing by it', () => {
    const knotsWithDuplicate = trailKnots({ stops: [0, 400, 400, 800], width: WIDTH, meanX: MEAN })
    expect(knotsWithDuplicate.length).toBeGreaterThan(4)
    for (const knot of knotsWithDuplicate) expect(Number.isFinite(knot.x) && Number.isFinite(knot.y)).toBe(true)
  })
})

describe('staying inside the box', () => {
  const { segments } = build()
  const points = sample(segments)

  /**
   * Half the stroke hangs outside the path on each side, and an SVG CLIPS at its viewBox. The
   * generator's default inset is 1.5, which is that half-stroke plus a hair.
   */
  it('keeps the ink and its stroke inside the width', () => {
    const half = 1.5 / 2
    const xs = points.map(([x]) => x)
    expect(Math.min(...xs) - half).toBeGreaterThan(0)
    expect(Math.max(...xs) + half).toBeLessThan(WIDTH)
  })

  it('uses most of the width it is given, rather than hugging the middle', () => {
    const xs = points.map(([x]) => x)
    // A path that only wandered a few pixels would pass the clipping test above and look like a wire.
    expect(Math.max(...xs) - Math.min(...xs)).toBeGreaterThan(WIDTH * 0.7)
  })

  it('never runs backwards up the page far enough to look like a mistake', () => {
    /* Loops go up and that is the point, so this is not monotonic — but outside a loop the path should
       be heading down. The bound is roughly the largest loop's diameter. */
    let worst = 0
    for (let i = 1; i < points.length; i += 1) {
      const rise = points[i - 1][1] - points[i][1]
      if (rise > worst) worst = rise
    }
    expect(worst).toBeLessThan(45)
  })
})

describe('no sharp points', () => {
  const { segments } = build()

  /**
   * C1 CONTINUITY AT EVERY JOIN. Centripetal Catmull-Rom guarantees it; this is what caught the
   * uniform version, whose cusps at the loops were visible on the page before anybody measured them.
   *
   * Compares DIRECTIONS rather than the tangent vectors themselves: consecutive segments are
   * parameterised over different arc lengths, so the magnitudes legitimately differ and only the
   * heading has to match.
   */
  it('turns smoothly at every junction between segments', () => {
    for (let i = 0; i < segments.length - 1; i += 1) {
      const leaving = tangents(segments[i]).end
      const arriving = tangents(segments[i + 1]).start
      const dot = leaving[0] * arriving[0] + leaving[1] * arriving[1]
      // 1 is a perfectly smooth join; anything approaching 0 is a corner.
      expect(dot, `junction ${i}`).toBeGreaterThan(0.985)
    }
  })

  it('has no zero-length segment, which would be a cusp with no direction at all', () => {
    for (const segment of segments) expect(arcLength([segment], 200)).toBeGreaterThan(0.2)
  })
})

describe('the loops', () => {
  const { segments } = build()

  /**
   * Self-intersections, found by looking for two samples that are far apart ALONG the curve and close
   * together in space. "Far apart along the curve" is what excludes neighbouring samples, which are
   * trivially close to each other.
   */
  const POINTS = sample(segments, 40)

  /**
   * Returns the SAMPLE RANGE of each crossing, not just where it happened — `[a, b]` are the indices
   * of the two passes through the same place, so `POINTS.slice(a, b)` is exactly the loop and nothing
   * else. Measuring a fixed radius around the crossing instead was the first attempt and it was wrong:
   * a 26px window also catches the path approaching and leaving, which stretched a round loop's
   * apparent bounding box to 25x46 and failed a shape that is fine.
   *
   * One entry per crossing: each true one produces a cloud of qualifying pairs, so only the first in
   * each neighbourhood is kept.
   */
  function loopRanges() {
    const ranges = []
    for (let a = 0; a < POINTS.length; a += 1) {
      for (let b = a + 40; b < POINTS.length; b += 1) {
        const distance = Math.hypot(POINTS[a][0] - POINTS[b][0], POINTS[a][1] - POINTS[b][1])
        if (distance >= 1.2) continue
        const already = ranges.some(([start]) => Math.abs(start - a) < 60)
        if (!already) ranges.push([a, b])
      }
    }
    return ranges
  }

  it('crosses itself several times, which is what makes them loops', () => {
    expect(loopRanges().length, 'distinct loops').toBeGreaterThanOrEqual(3)
  })

  /**
   * ROUND, NOT PINCHED. A loop's bounding box tells you which: a circle's is square, and the oval the
   * tiled version was squeezed into measured 17.7 by 23. Measured over the samples belonging to each
   * loop, found by taking every sample within a radius of the crossing point.
   */
  it('draws loops that are roughly as wide as they are tall', () => {
    const ranges = loopRanges()
    expect(ranges.length).toBeGreaterThanOrEqual(3)
    for (const [a, b] of ranges) {
      const loop = POINTS.slice(a, b + 1)
      const width = Math.max(...loop.map(([x]) => x)) - Math.min(...loop.map(([x]) => x))
      const height = Math.max(...loop.map(([, y]) => y)) - Math.min(...loop.map(([, y]) => y))
      const ratio = Math.min(width, height) / Math.max(width, height)
      /* A circle is 1.0. The oval the tiled version was squeezed into measured 17.7 by 23, a ratio of
         0.77 — so the floor is set below that on purpose, to catch the shape that prompted the
         rewrite rather than to demand a perfect circle from a hand-drawn-looking curve. */
      expect(ratio, `loop measured ${width.toFixed(1)}x${height.toFixed(1)}`).toBeGreaterThan(0.72)
    }
  })

  it('draws them big enough to read as loops', () => {
    for (const [a, b] of loopRanges()) {
      const loop = POINTS.slice(a, b + 1)
      const width = Math.max(...loop.map(([x]) => x)) - Math.min(...loop.map(([x]) => x))
      // MIN_LOOP is a radius of 9, so the smallest loop is about 18 across.
      expect(width, `loop ${width.toFixed(1)} across`).toBeGreaterThan(16)
    }
  })

  /**
   * Pull the loops out of a knot list.
   *
   * A loop is the six knots `loopKnots` appends, five of which are off the mean line, and it is always
   * preceded immediately by a swing crest — so an off-mean run of five or more is a loop and its last
   * five knots are the circle. A run of one is an ordinary crest.
   *
   * BOTH OF THE TESTS BELOW USED TO MEASURE SOMETHING ELSE, and both passed while the generator was
   * putting every loop on the same side at nearly the same size. One checked the sampled extremes of
   * the whole curve, which the WAVES satisfy on their own; the other measured crest-plus-loop runs and
   * so compared numbers dominated by the crest. This helper is what makes them about loops.
   */
  function loopsIn(knots, meanX) {
    const runs = []
    let run = []
    for (const knot of knots) {
      if (Math.abs(knot.x - meanX) > 2) run.push(knot)
      else {
        if (run.length >= 5) runs.push(run.slice(-5))
        run = []
      }
    }
    if (run.length >= 5) runs.push(run.slice(-5))
    return runs.map((circle) => {
      const xs = circle.map((knot) => knot.x)
      const centre = (Math.max(...xs) + Math.min(...xs)) / 2
      return { side: centre > meanX ? 1 : -1, extent: Math.max(...xs) - Math.min(...xs) }
    })
  }

  /**
   * A DISTRIBUTION test over many spans rather than over one page, and deliberately so: the side is
   * weighted about 62/38 toward whichever side has more room, so a single page of five or six loops
   * legitimately comes out all on one side about one time in ten. Asserting against one page would be
   * a flaky test; asserting against 300 spans is a fact about the generator.
   */
  const sampled = Array.from({ length: 300 }, (_, i) =>
    loopsIn(trailKnots({ stops: [0, 430], width: WIDTH, meanX: MEAN, seed: 20271008 + i }), MEAN),
  ).flat()

  it('uses both sides of the mean line, given room on both', () => {
    const left = sampled.filter((loop) => loop.side < 0).length
    const right = sampled.length - left
    expect(sampled.length, 'loops sampled').toBeGreaterThan(100)
    /* Neither side may vanish. The roomier one should be the more common — that is the point of the
       weighting — but a generator that never used the other would be repetitive in the way that is
       hardest to see, and is exactly what a correlated seed produced. */
    expect(left / sampled.length).toBeGreaterThan(0.25)
    expect(right / sampled.length).toBeGreaterThan(0.15)
  })

  it('varies their size across most of the range the band allows', () => {
    const extents = sampled.map((loop) => loop.extent).sort((a, b) => a - b)
    const smallest = extents[0]
    const largest = extents[extents.length - 1]
    // A correlated seed gave a spread of 3px across a whole page. Anything under 8 is stamping.
    expect(largest - smallest, `${smallest.toFixed(1)}..${largest.toFixed(1)}`).toBeGreaterThan(8)
  })

  it('draws more big loops than small ones, since big is the whole point', () => {
    const extents = sampled.map((loop) => loop.extent)
    const midpoint = (Math.min(...extents) + Math.max(...extents)) / 2
    const big = extents.filter((extent) => extent > midpoint).length
    // The radius is drawn with a sqrt bias toward the top of the range; uniform put the median at the
    // bottom of it and the page read as a row of little curls.
    expect(big / extents.length).toBeGreaterThan(0.4)
  })

  it('leaves them out where the band is too narrow to hold a round one', () => {
    // A 24px band gives a maximum radius of about 10 on each side, so loops become sparse or absent
    // rather than being drawn pinched.
    const narrow = trailKnots({ stops: STOPS, width: 24, meanX: 12 })
    for (const knot of narrow) {
      expect(Math.abs(knot.x - 12)).toBeLessThanOrEqual(12)
    }
  })
})

describe('not repeating', () => {
  it('gives no two spans the same shape', () => {
    const shapes = new Set()
    for (let span = 0; span < STOPS.length - 1; span += 1) {
      const knots = trailKnots({
        stops: [0, STOPS[span + 1] - STOPS[span]],
        width: WIDTH,
        meanX: MEAN,
        seed: 20271008 + span * 7919,
      })
      shapes.add(knots.map((knot) => `${knot.x.toFixed(1)},${knot.y.toFixed(1)}`).join('|'))
    }
    expect(shapes.size).toBe(STOPS.length - 1)
  })

  it('does not put its crests at a regular interval', () => {
    const { knots } = build()
    const crests = knots.filter((knot) => Math.abs(knot.x - MEAN) > 8).map((knot) => knot.y)
    const gaps = crests.slice(1).map((y, i) => y - crests[i]).filter((gap) => gap > 20)
    const mean = gaps.reduce((sum, gap) => sum + gap, 0) / gaps.length
    const spread = Math.sqrt(gaps.reduce((sum, gap) => sum + (gap - mean) ** 2, 0) / gaps.length)
    // A tiled path had a spread of exactly zero. Anything above a tenth of the mean reads as hand-placed.
    expect(spread / mean).toBeGreaterThan(0.1)
  })
})

describe('stability', () => {
  it('is identical for identical input', () => {
    expect(trailPath({ stops: STOPS, width: WIDTH, meanX: MEAN })).toBe(
      trailPath({ stops: STOPS, width: WIDTH, meanX: MEAN }),
    )
  })

  /**
   * THE REASON THE GENERATOR SEEDS PER SPAN. The path is rebuilt on every reflow, so opening one FAQ
   * row must not redraw the whole trail differently — with a single random stream it would, because
   * every later draw would shift.
   */
  it('leaves the spans above a change untouched when one span grows', () => {
    const grown = [...STOPS]
    for (let i = 5; i < grown.length; i += 1) grown[i] += 120

    const before = trailKnots({ stops: STOPS, width: WIDTH, meanX: MEAN })
    const after = trailKnots({ stops: grown, width: WIDTH, meanX: MEAN })

    const upTo = (knots, y) => knots.filter((knot) => knot.y <= y).map((k) => `${k.x.toFixed(2)},${k.y.toFixed(2)}`)
    expect(upTo(after, STOPS[4])).toEqual(upTo(before, STOPS[4]))
  })

  it('changes shape when the seed changes, so the seed is actually wired up', () => {
    expect(trailPath({ stops: STOPS, width: WIDTH, meanX: MEAN, seed: 1 })).not.toBe(
      trailPath({ stops: STOPS, width: WIDTH, meanX: MEAN, seed: 2 }),
    )
  })
})

describe('the pre-measurement estimate', () => {
  it('produces one more stop than there are waypoints, for the summit mark', () => {
    expect(estimatedStops(8)).toHaveLength(9)
    expect(estimatedStops(8)[0]).toBe(0)
  })

  it('is always usable, even for a page with nothing on it', () => {
    expect(estimatedStops(0).length).toBeGreaterThanOrEqual(2)
    expect(trailPath({ stops: estimatedStops(0), width: WIDTH, meanX: MEAN })).toMatch(/^M[\d.]+ [\d.]+C/)
  })
})

describe('knotsToPath', () => {
  it('emits one cubic per gap between knots', () => {
    const knots = [
      { x: 0, y: 0 },
      { x: 10, y: 10 },
      { x: 0, y: 20 },
      { x: 10, y: 30 },
    ]
    expect(parseCubicPath(knotsToPath(knots))).toHaveLength(3)
  })

  it('passes through every knot it was given', () => {
    const knots = [
      { x: 5, y: 0 },
      { x: 20, y: 40 },
      { x: 5, y: 90 },
    ]
    const segments = parseCubicPath(knotsToPath(knots))
    expect(segments[0][0]).toEqual([5, 0])
    expect(segments[0][3]).toEqual([20, 40])
    expect(segments[1][3]).toEqual([5, 90])
  })

  it('survives two coincident knots without producing NaN', () => {
    const d = knotsToPath([
      { x: 5, y: 0 },
      { x: 10, y: 10 },
      { x: 10, y: 10 },
      { x: 5, y: 20 },
    ])
    expect(d).not.toContain('NaN')
  })
})

/* ---- The hero's rule, which is still an SVG in a url() ------------------ */

const appCss = readFileSync('src/styles/app.css', 'utf8')
const tokensCss = readFileSync('src/styles/tokens.css', 'utf8')

function extractSvg(css, selector) {
  const rule = new RegExp(`${selector}\\s*\\{([^}]*)\\}`).exec(css)
  expect(rule, `rule for ${selector}`).not.toBe(null)
  const uri = /url\("data:image\/svg\+xml,([^"]+)"\)/.exec(rule[1])
  expect(uri, `data URI in ${selector}`).not.toBe(null)
  return uri[1].replace(/%3C/g, '<').replace(/%3E/g, '>').replace(/%23/g, '#')
}

function attribute(svg, name) {
  const match = new RegExp(`${name}='([^']*)'`).exec(svg)
  expect(match, `${name} attribute`).not.toBe(null)
  return match[1]
}

describe("the hero's rule", () => {
  const svg = extractSvg(appCss, '\\.hero__rule')
  const segments = parseCubicPath(attribute(svg, 'd'))
  const [dash, gap] = attribute(svg, 'stroke-dasharray').split(/\s+/).map(Number)
  const length = arcLength(segments)

  it('is one full wave', () => {
    expect(segments).toHaveLength(2)
  })

  /**
   * Not tiled, so it is free of the whole-multiple constraint the trail used to be under — but only in
   * one direction. The period still has to leave the pattern ENDING on a dash rather than mid-gap, or
   * the rule looks cropped: length = k * period + dash, for a whole k.
   */
  it('ends on a dash rather than mid-gap', () => {
    const k = (length - dash) / (dash + gap)
    expect(k).toBeCloseTo(Math.round(k), 3)
    expect(Math.round(k)).toBe(8)
  })

  it("shares the trail's dash rhythm closely enough to look deliberate", () => {
    /* The trail draws 3.4/6 from TrailPath.jsx. These cannot be one token — one is an inline SVG's
       attribute and the other is inside a `url()` — so the agreement is asserted instead. */
    expect(Math.abs(dash + gap - 9.4)).toBeLessThan(0.6)
  })

  it('draws in the trail colour, which it cannot inherit', () => {
    const trail = /--trail:\s*(#[0-9a-fA-F]{6})/.exec(tokensCss)[1]
    expect(attribute(svg, 'stroke').toLowerCase()).toBe(trail.toLowerCase())
  })

  it('is redrawn in white over a photograph, where the brown has no measured contrast', () => {
    const overPhoto = extractSvg(appCss, '\\.hero--photo \\.hero__rule')
    expect(attribute(overPhoto, 'stroke').toLowerCase()).toBe('#ffffff')
    // Same path and same rhythm — only the stroke may differ, or the two heroes stop matching.
    expect(attribute(overPhoto, 'd')).toBe(attribute(svg, 'd'))
    expect(attribute(overPhoto, 'stroke-dasharray')).toBe(attribute(svg, 'stroke-dasharray'))
  })
})

describe('the retired tile', () => {
  const trailCss = readFileSync('src/styles/trail.css', 'utf8')

  it('leaves no tiled background behind in trail.css', () => {
    // Strip comments first: the file explains at length what it used to do, and a raw search would
    // match that prose and pass whatever the rules say.
    const code = trailCss.replace(/\/\*[\s\S]*?\*\//g, '')
    expect(code).not.toContain('background-image')
    expect(code).not.toContain('repeat-y')
    expect(code).not.toMatch(/--trail-tile/)
  })

  it('gives the drawing a box wider than the trail gutter, which is what the loops need', () => {
    const rule = /\.trail__drawing\s*\{([^}]*)\}/.exec(trailCss)[1]
    // Reaching back across the page's own padding is the whole trick.
    expect(rule).toContain('left: calc(-1 * var(--space-4))')
    expect(rule).toContain('color: var(--trail)')
  })
})
